
[functions.generate-content-from-ai]
enabled = true
verify_jwt = true
import_map = "./functions/generate-content-from-ai/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-content-from-ai/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-content-from-ai/*.html" ]

[functions.update-leaderboard]
enabled = true
verify_jwt = true
import_map = "./functions/update-leaderboard/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-leaderboard/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-leaderboard/*.html" ]
